In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("financial_transactions.csv")

In [6]:
df.head()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status
0,1001,1/5/2026,C001,Router,1,25000,transfer,pending
1,1002,1/6/2026,C002,Phone,1,15000,card,completed
2,1003,1/7/2026,C003,Laptop,2,20000,transfer,pending
3,1004,1/8/2026,C004,Headphone,3,3000,cash,completed
4,1005,1/9/2026,C005,Tablet,4,4000,cash,completed

In [7]:
df.shape

(10, 8)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      10 non-null     int64
 1   transaction_date    10 non-null     str
 2   customer_id         10 non-null     str
 3   product_name        10 non-null     str
 4   quantity            10 non-null     int64
 5   price               10 non-null     int64
 6   payment_method      10 non-null     str
 7   transaction_status  10 non-null     str
dtypes: int64(3), str(5)
memory usage: 772.0 bytes

In [9]:
df.isnull().sum()

transaction_id        0
transaction_date      0
customer_id           0
product_name          0
quantity              0
price                 0
payment_method        0
transaction_status    0
dtype: int64

In [58]:
df.columns = df.columns.str.lower()

In [59]:
df.columns

Index(['transaction_id', 'transaction_date', 'customer_id', 'product_name',
       'quantity', 'price', 'payment_method', 'transaction_status',
       'total_value', 'transaction_type'],
      dtype='str')

In [56]:
df["price"].median()

np.float64(15000.0)

In [57]:
df["price"] = df["price"].fillna(df["price"].median())

In [53]:
df["product_name"] = df["product_name"].str.strip().str.lower()
df["payment_method"] = df["payment_method"].str.strip().str.lower()
df["transaction_status"] = df["transaction_status"].str.strip().str.lower()
df["customer_id"] = df["customer_id"].str.strip().str.lower()

In [54]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors="coerce")

In [55]:
df = df.drop_duplicates()

In [45]:
df["total_value"] = df["quantity"] * df["price"]

In [43]:
df = pd.read_csv("financial_transactions.csv")

In [48]:
df.head()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status,total_value
0,1001,1/5/2026,C001,Router,1,25000,transfer,pending,25000
1,1002,1/6/2026,C002,Phone,1,15000,card,completed,15000
2,1003,1/7/2026,C003,Laptop,2,20000,transfer,pending,40000
3,1004,1/8/2026,C004,Headphone,3,3000,cash,completed,9000
4,1005,1/9/2026,C005,Tablet,4,4000,cash,completed,16000

In [49]:
def my_function(x):
    if x >= 100:
        return "bulk"
    else:
        return "regular"

df["transaction_type"] = df["quantity"].apply(my_function)

In [50]:
df[["quantity", "transaction_type"]].head()

   quantity transaction_type
0         1          regular
1         1          regular
2         2          regular
3         3          regular
4         4          regular

In [60]:
df.head()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status,total_value,transaction_type
0,1001,2026-01-05,c001,router,1,25000,transfer,pending,25000,regular
1,1002,2026-01-06,c002,phone,1,15000,card,completed,15000,regular
2,1003,2026-01-07,c003,laptop,2,20000,transfer,pending,40000,regular
3,1004,2026-01-08,c004,headphone,3,3000,cash,completed,9000,regular
4,1005,2026-01-09,c005,tablet,4,4000,cash,completed,16000,regular

In [61]:
df["year"] = df["transaction_date"].dt.year

In [62]:
df.head()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status,total_value,transaction_type,year
0,1001,2026-01-05,c001,router,1,25000,transfer,pending,25000,regular,2026
1,1002,2026-01-06,c002,phone,1,15000,card,completed,15000,regular,2026
2,1003,2026-01-07,c003,laptop,2,20000,transfer,pending,40000,regular,2026
3,1004,2026-01-08,c004,headphone,3,3000,cash,completed,9000,regular,2026
4,1005,2026-01-09,c005,tablet,4,4000,cash,completed,16000,regular,2026

In [63]:
df["month"] = df["transaction_date"].dt.month

In [64]:
df.head()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status,total_value,transaction_type,year,month
0,1001,2026-01-05,c001,router,1,25000,transfer,pending,25000,regular,2026,1
1,1002,2026-01-06,c002,phone,1,15000,card,completed,15000,regular,2026,1
2,1003,2026-01-07,c003,laptop,2,20000,transfer,pending,40000,regular,2026,1
3,1004,2026-01-08,c004,headphone,3,3000,cash,completed,9000,regular,2026,1
4,1005,2026-01-09,c005,tablet,4,4000,cash,completed,16000,regular,2026,1

In [65]:
def high_value(total):
    if total > 2000:
        return True
    else:
        return False
df["high_value"] = df["total_value"].apply(high_value)

In [66]:
df.head()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status,total_value,transaction_type,year,month,high_value
0,1001,2026-01-05,c001,router,1,25000,transfer,pending,25000,regular,2026,1,True
1,1002,2026-01-06,c002,phone,1,15000,card,completed,15000,regular,2026,1,True
2,1003,2026-01-07,c003,laptop,2,20000,transfer,pending,40000,regular,2026,1,True
3,1004,2026-01-08,c004,headphone,3,3000,cash,completed,9000,regular,2026,1,True
4,1005,2026-01-09,c005,tablet,4,4000,cash,completed,16000,regular,2026,1,True

In [ ]:
def categorize_revenue(total):
    if total < 500:
        return "low"
    elif 500 <= total <= 2000:
        return "medium"
    else:  # total > 2000
        return "high"


df["revenue_category"] = df["total_value"].apply(categorize_revenue)

In [79]:
df["transaction_weekday"] = df["transaction_date"].dt.day_name()

In [80]:
df.head()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status,total_value,transaction_type,year,month,high_value,transaction_weekday
0,1001,2026-01-05,c001,router,1,25000,transfer,pending,25000,regular,2026,1,True,Monday
1,1002,2026-01-06,c002,phone,1,15000,card,completed,15000,regular,2026,1,True,Tuesday
2,1003,2026-01-07,c003,laptop,2,20000,transfer,pending,40000,regular,2026,1,True,Wednesday
3,1004,2026-01-08,c004,headphone,3,3000,cash,completed,9000,regular,2026,1,True,Thursday
4,1005,2026-01-09,c005,tablet,4,4000,cash,completed,16000,regular,2026,1,True,Friday

In [81]:
df.tail()

,transaction_id,transaction_date,customer_id,product_name,quantity,price,payment_method,transaction_status,total_value,transaction_type,year,month,high_value,transaction_weekday
5,1006,2026-01-10,c006,radio,2,3000,cash,completed,6000,regular,2026,1,True,Saturday
6,1007,2026-01-11,c007,pods,4,5000,transfer,completed,20000,regular,2026,1,True,Sunday
7,1008,2026-01-12,c008,car,2,50000,transfer,pending,100000,regular,2026,1,True,Monday
8,1009,2026-01-13,c009,bike,6,20000,card,pending,120000,regular,2026,1,True,Tuesday
9,1010,2026-01-14,c010,bed,6,15000,cash,completed,90000,regular,2026,1,True,Wednesday

In [69]:
df.to_csv("clean_transactions.csv", index="false")

In [77]:
def clean_transaction_data(file_name):
    import pandas as pd
    
    df = pd.read_csv("financial_transactions.csv")

    df.columns = df.columns.str.lower()

    df["price"].median()

    df["price"] = df["price"].fillna(df["price"].median())

    df["product_name"] = df["product_name"].str.strip().str.lower()
    df["payment_method"] = df["payment_method"].str.strip().str.lower()
    df["transaction_status"] = df["transaction_status"].str.strip().str.lower()
    df["customer_id"] = df["customer_id"].str.strip().str.lower()

    df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors="coerce")

    df = df.drop_duplicates()

    df["total_value"] = df["quantity"] * df["price"]

    def my_function(x):
        if x >= 100:
            return "bulk"
        else:
            return "regular"

    df["transaction_type"] = df["quantity"].apply(my_function)

    df["year"] = df["transaction_date"].dt.year

    df["month"] = df["transaction_date"].dt.month


    def high_value(total):
        if total > 2000:
            return True
        else:
            return False
        df["high_value"] = df["total_value"].apply(high_value) 


    def categorize_revenue(total):
        if total < 500:
            return "low"
        elif 500 <= total <= 2000:
            return "medium"
        else:  # total > 2000
            return "high"


    df["revenue_category"] = df["total_value"].apply(categorize_revenue) 


    df["transaction_weekday"] = df["transaction_date"].dt.day_name()

    
    df.to_csv("clean_transactions.csv", index="false")

    return df

In [78]:
clean_df = clean_transaction_data("financial_transactions.csv")